---
- name: Deploy Spring Boot App
  hosts: localhost
  tasks:
    - name: Copy JAR file
      ansible.builtin.copy:
        src: "C:/Users/Indumathi/Downloads/ansible/ansible/target/ansible-0.0.1-SNAPSHOT.jar"
        dest: /opt/app/app.jar

    - name: Start Application
      ansible.builtin.command: java -jar /opt/app/app.jar --server.port={{ server_port }}
      async: 3600
      poll: 0
